# Default values for logsidecar-injector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

enabled: false

global:
  clusterInfo:
    name: ""

hook:
  postInstall:
    image:
      repo: bitnami/kubectl
      tag: 1.26.13
      pullPolicy: IfNotPresent
    backoffLimit: 1

image:
  repository: kubesphere/log-sidecar-injector
  tag: "" # If unset use v+ .Chart.appVersion
  pullPolicy: IfNotPresent

imagePullSecrets: []

resources: {}
#  limits:
#    cpu: 100m
#    memory: 100Mi
#  requests:
#    cpu: 10m
#    memory: 10Mi

configReloader:
  image:
    repository: jimmidyson/configmap-reload
    tag: v0.7.1
    pullPolicy: IfNotPresent
  resources: {}
#    limits:
#      cpu: 100m
#      memory: 100Mi
#    requests:
#      cpu: 10m
#      memory: 10Mi

sidecar:
  sidecarType: vector
  filebeatContainer:
    image:
      repository: elastic/filebeat
      tag: 6.7.0
      pullPolicy: IfNotPresent
    resources: {}
  vectorContainer:
    image:
      repository: timberio/vector
      tag: 0.34.1-distroless-static
      pullPolicy: IfNotPresent
    resources: {}
  initContainer:
    image:
      repository: alpine
      tag: 3.14
      pullPolicy: IfNotPresent
    resources: {}