# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ippool:
  type: "calico"

apiserver:
  replicas: 1
  image:
    repository: registry.cn-beijing.aliyuncs.com/kse/network-extension-apiserver
    pullPolicy: IfNotPresent
    tag: "v1.0.0"
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 30m
      memory: 50Mi

controller:
  replicas: 1
  image:
    repository: registry.cn-beijing.aliyuncs.com/kse/network-extension-controller
    pullPolicy: IfNotPresent
    tag: "v1.0.0"
  service:
    type: ClusterIP
    port: 443
  resources:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 30m
      memory: 50Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}
