agent:
  jenkins:
    securityRealm:
      openIdConnect:
        # The kubesphere-core api used for jenkins OIDC
        # If want to access to jenkinsUI, the kubesphereCoreApi must be specified and browser-accessible
        # Modifying this configuration will take effect during installation
        # If you wish for changes to take effect after installation, you need to update the jenkins-casc-config ConfigMap，copy the securityRealm configuration from jenkins.yaml to jenkins_user.yaml, save, and wait for approximately 70 seconds for the changes to take effect.
        kubesphereCoreApi: "http://ks-apiserver.kubesphere-system.svc:30881"
    Master:
      resources:
        requests:
          cpu: 0.5
          memory: 6Gi
        limits:
          cpu: 2
          memory: 6Gi # Set same as requests.memory
    Persistence:
      size: 16Gi
      StorageClass: "-"
      AccessMode: ReadWriteOnce
      #  ExistingClaim: ""
