{{- if .Values.storageclassAccessor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: storage-utils-webhook
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
{{- end }}