kind: CronJob
{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
metadata:
  name: {{ include "ks-devops.name" . }}
  namespace: {{ default .Release.Namespace .Values.global.namespace }}
  labels:
    app: devops-pipelinerun-gcjobs
spec:
  concurrencyPolicy: {{ .Values.gcJobs.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.gcJobs.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ include "ks-devops.name" . }}
            release: {{ .Release.Name }}
{{- if .Values.gcJobs.podAnnotations }}
          annotations:
{{ toYaml .Values.gcJobs.podAnnotations | indent 12 }}
{{- end }}
        spec:
          {{- with (default .Values.global.image.pullSecrets .Values.gcJobs.image.pullSecrets) }}
          imagePullSecrets:
          {{- toYaml . | nindent 12 }}
          {{- end -}}
          containers:
            - command:
                - ks
                - pip
                - gc
              image: "{{ default .Values.gcJobs.image.registry .Values.global.image.registry }}/{{ .Values.gcJobs.image.repository }}:{{ .Values.gcJobs.image.tag }}"
              imagePullPolicy: {{ .Values.gcJobs.image.pullPolicy }}
              args:
                - "--max-count={{ .Values.gcJobs.maxCount }}"
                - "--max-age={{ .Values.gcJobs.maxAge }}"
                - "--condition=ignoreTime"
              name: "pipeline-run-gc"
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          serviceAccountName: {{ .Values.serviceAccount.name }}
  successfulJobsHistoryLimit: {{ .Values.gcJobs.successfulJobsHistoryLimit }}
  schedule: {{ .Values.gcJobs.schedule | quote }}
  startingDeadlineSeconds: 4000
  suspend: false
