apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ks-devops.controller-fullname" . }}
  namespace: {{ default .Release.Namespace .Values.global.namespace }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.controller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "controller.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: kubesphere-config
          configMap:
            name: devops-config
            defaultMode: 420
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.controller.repository }}:{{ .Values.image.controller.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - '--pipelinerun-data-store=configmap'
          - '--enabled-controllers'
          {{- if .Values.argocd.enabled }}
          - argocd=true
          - --argocd-namespace={{ default .Release.Namespace .Values.argocd.namespace }}
          {{- end}}
          env:
            - name: JENKINS_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: devops-jenkins
                  key: jenkins-admin-token
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          volumeMounts:
            - name: kubesphere-config
              mountPath: /etc/kubesphere/
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
