{{- if .Values.global.namespace }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-agent-pre-install"
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: pre-install-job
          {{- if .Values.global.image.registry }}
          image: "kubesphere/kubectl:v1.27.4"
          {{- else }}
          image: "{{ .Values.global.image.registry }}/kubesphere/kubectl:v1.27.4"
          {{- end -}}
          command: ["/bin/bash","-c","\n
            for NS in kubesphere-devops-system kubesphere-devops-worker argocd; \n
            do \n
              if kubectl get namespace $NS &>/dev/null; then \n
                echo \"Namespace $NS already exists. Skipping...\" \n
              else \n
                kubectl create namespace $NS && kubectl label ns $NS kubesphere.io/workspace=system-workspace; \n
              fi \n
            done;"]
{{- end }}
