{{- if .Values.service.enabled -}}
apiVersion: monitoring.whizard.io/v1alpha1
kind: Service
metadata:
  name: {{ include "whizard.service.crname" . }}
  namespace: {{ include "whizard.namespace" . }}
  labels:
    {{- include "whizard.labels" . | nindent 4 }}
spec:
  tenantHeader: {{ .Values.service.tenantHeader }}
  defaultTenantId: {{ .Values.service.defaultTenantId }}
  tenantLabelName: {{ .Values.service.tenantLabelName }}
  {{- if .Values.service.storage }}
  storage:
    {{- toYaml .Values.service.storage | nindent 4 }}
  {{- else if and .Values.storage.create .Values.storage.S3 }}
  storage:
    name: {{ include "whizard.storage.crname" . }}
    namespace: {{ include "whizard.namespace" . }}
  {{- end }}
  {{- if .Values.service.remoteWrites }}
  remoteWrites:
    {{- toYaml .Values.service.remoteWrites | nindent 4 }}
  {{- end }}
  {{- if .Values.service.remoteQuery }}
  remoteQuery:
    {{- toYaml .Values.service.remoteQuery | nindent 4 }}
  {{- end }}
{{- end }}
