{{- $ca := genCA "webhook-ca" 36500 -}}
{{- $dns := cat "whizard-telemetry-ruler-svc." .Release.Namespace ".svc" | nospace -}}
{{- $cert := genSignedCert "whizard-telemetry-ruler-svc" (list) (list $dns) 36500 $ca -}}
apiVersion: v1
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key  | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
kind: Secret
metadata:
  name: whizard-telemetry-ruler-secret
type: kubernetes.io/tls