kind: Service
apiVersion: v1
metadata:
  name: whizard-telemetry-ruler-svc
spec:
  ports:
    - name: event
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: whizard-telemetry-ruler
  type: ClusterIP
