apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}-apiserver
  labels:
    app: ippool-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.apiserver.service.type }}
  ports:
    - port: {{ .Values.apiserver.service.port }}
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    app: ippool-apiserver
