---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ippool-controller-role
  labels:
    app: ippool-controller
rules:
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - get
    - create
    - patch
    - update
  - apiGroups:
    - ""
    resources:
    - pods
    - namespaces
    verbs:
    - get
    - watch
    - list
    - update
    - patch
  - apiGroups:
    - "apps"
    resources:
    - deployments
    - daemonsets
    - statefulsets
    verbs:
    - get
    - watch
    - list
    - update
    - patch
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases/status
    verbs:
    - get
    - update
    - patch
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - ipamblocks
    - ipamhandles
    - blockaffinities
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - ippools
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
    