{{- if and .Values.query.enabled .Values.query.genSignedCert -}}

{{- $ca := genCA "query-whizard-ca" 3650 }}
{{- $cn := printf "%s"  (include "whizard.query.crname" .) }}
{{- $altName1 := printf "query-%s-operated.%s" (include "whizard.query.crname" .) (include "whizard.namespace" .) }}
{{- $altName2 := printf "query-%s-operated.%s.svc" (include "whizard.query.crname" .) (include "whizard.namespace" .)}}
{{- $querytlscert := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "whizard.query.crname" . }}-query-tls-assets
  namespace: {{ include "whizard.namespace" . }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $querytlscert.Cert | b64enc | quote }}
  tls.key: {{ $querytlscert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}

{{- end }}