{{- if .Values.global.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "whizard-telemetry.fullname" . }}
  labels:
    {{- include "whizard-telemetry.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - secrets
    - configmaps
  verbs:
    - '*'
- apiGroups:
    - "notification.kubesphere.io"
  resources:
    - '*'
  verbs:
    - '*'
{{- if .Values.config.monitoring.enabled }}
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - get
    - list
    - watch
{{- end }}
{{- end }}