apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whizard-telemetry.fullname" . }}-apiserver
  namespace: {{ include "whizard-telemetry.namespace" . }}
  labels:
    app: whizard-telemetry-apiserver
    tier: backend  
    {{- include "whizard-telemetry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiserver.replicaCount }}
  selector:
    matchLabels:
      app: whizard-telemetry-apiserver
      tier: backend    
      {{- include "whizard-telemetry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubesphere.io/serviceaccount-name: {{ include "whizard-telemetry.ksServiceAccountName" . }}
      {{- with .Values.apiserver.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: whizard-telemetry-apiserver
        tier: backend  
        {{- include "whizard-telemetry.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.apiserver.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "whizard-telemetry.serviceAccountName" . }}
      {{- with .Values.apiserver.podSecurityContext }}      
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          command:
          - apiserver
          - --logtostderr=true
          {{- with .Values.apiserver.securityContext }}             
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.apiserver.image.repository }}:{{ .Values.apiserver.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.apiserver.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.apiserver.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.apiserver.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /etc/whizard-telemetry/
            name: whizard-telemetry-config
          - mountPath: /etc/localtime
            name: host-time
            readOnly: true
          {{- if .Values.apiserver.extraVolumeMounts }}
            {{- toYaml .Values.apiserver.extraVolumeMounts | nindent 10 }}
          {{- end }}
      {{- with .Values.apiserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ include "whizard-telemetry.fullname" . }}-config
        name: whizard-telemetry-config
      - hostPath:
          path: /etc/localtime
          type: ""
        name: host-time
      {{- if .Values.apiserver.extraVolumes }}
        {{ toYaml .Values.apiserver.extraVolumes | nindent 6 }}
      {{- end }}
