{{- if .Values.ksRbac.create }}
apiVersion: iam.kubesphere.io/v1beta1
kind: GlobalRole
metadata:
  name: {{ include "whizard-telemetry.fullname" . }}-anonymous
rules:
  - nonResourceURLs:
      - /proxy/alerting.kubesphere.io/v2beta1/*
    verbs:
      - '*'
{{- end }}