{{- if .Values.ksRbac.create }}
apiVersion: iam.kubesphere.io/v1beta1
kind: GlobalRoleBinding
metadata:
  name: {{ include "whizard-telemetry.fullname" . }}-anonymous
roleRef:
  apiGroup: iam.kubesphere.io
  kind: GlobalRole
  name: {{ include "whizard-telemetry.fullname" . }}-anonymous
subjects:
  - apiGroup: iam.kubesphere.io
    kind: Group
    name: system:authenticated
{{- end }}