{{- if .Values.ksServiceAccount.create }}
apiVersion: kubesphere.io/v1alpha1
kind: ServiceAccount
metadata:
  name: {{ include "whizard-telemetry.ksServiceAccountName" . }}
  namespace: {{ include "whizard-telemetry.namespace" . }}
  labels:
    {{- include "whizard-telemetry.labels" . | nindent 4 }}
{{- end }}