{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "whizard-telemetry.serviceAccountName" . }}
  namespace: {{ include "whizard-telemetry.namespace" . }}
  labels:
    {{- include "whizard-telemetry.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- if .Values.global.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "whizard-telemetry.fullname" . }}
  labels:
    {{- include "whizard-telemetry.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - secrets
    - configmaps
  verbs:
    - '*'
- apiGroups:
    - "notification.kubesphere.io"
  resources:
    - '*'
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - "tenant.kubesphere.io"
  resources:
    - workspaces
  verbs:
    - get
    - list
    - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "whizard-telemetry.fullname" . }}
  labels:
    {{- include "whizard-telemetry.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "whizard-telemetry.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "whizard-telemetry.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}