#frontend:
#  enabled: true

backend:
  enabled: true
  # Specifies whether the servicemesh-config configmap
  config:
    servicemesh:
      jaegerQueryHost: http://jaeger-query.extension-servicemesh.svc:16686
      kialiQueryHost: http://kiali.extension-servicemesh.svc:20001

  ## istio
  istiod:
    # tracing configuration
    meshConfig:
      defaultConfig:
        tracing:
          zipkin:
            address: jaeger-collector.extension-servicemesh.svc:9411
        sampling: 1.0

  ## kiali
  kiali:
    prometheus_url: http://prometheus-operated.kubesphere-monitoring-system.svc:9090

  ## jaeger-operator
  # jaeger-operator:
  #   certs:
  #     issuer:
  #       create: true
  #     certificate:
  #       create: true
  #       namespace: ""
  #       secretName: ""

  ## jaeger
  jaeger:
    storage:
      options:
        es:
          server-urls: https://opensearch-cluster-master.kubesphere-logging-system.svc:9200
          username: admin
          password: admin
      #  secretName: jaeger-secret-opensearch