apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-post-install
  namespace: {{ include "history.namespaceOverride" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-post-install
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
rules:
  - apiGroups:
      - notification.kubesphere.io
    resources:
      - 'notificationmanagers'
    verbs:
      - '*'

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-post-install
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-post-install
    namespace: {{ include "history.namespaceOverride" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-post-install
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-post-install
  namespace: {{ include "history.namespaceOverride" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
spec:
  backoffLimit: 1
  template:
    metadata:
      name: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Release.Name }}-post-install
      containers:
        - name: post-install-job
          image: {{ .Values.hook.image.repo }}:{{ .Values.hook.image.tag }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              cat > /tmp/patch.yaml <<EOF
              spec:
                history:
                  webhook:
                    enabled: true
                    service:
                      name: vector-aggregator
                      namespace: {{ include "history.namespaceOverride" . }}
                      path: notification-history
                      port: 6001
                    template: nm.default.history
              EOF

              kubectl patch notificationmanagers.notification.kubesphere.io notification-manager --type=merge --patch-file /tmp/patch.yaml
