apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-pre-delete
  namespace: {{ include "history.namespaceOverride" . }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-pre-delete
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
rules:
  - apiGroups:
      - notification.kubesphere.io
    resources:
      - 'notificationmanagers'
    verbs:
      - '*'

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-pre-delete
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-pre-delete
    namespace: {{ include "history.namespaceOverride" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-pre-delete
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-pre-delete
  namespace: {{ include "history.namespaceOverride" . }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
spec:
  backoffLimit: 1
  template:
    metadata:
      name: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Release.Name }}-pre-delete
      containers:
        - name: pre-delete-job
          image: {{ .Values.hook.image.repo }}:{{ .Values.hook.image.tag }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              kubectl patch notificationmanagers.notification.kubesphere.io notification-manager --type='json' -p='[{"op": "remove", "path": "/spec/history"}]'
