{{- if .Values.router.enabled -}}
apiVersion: monitoring.whizard.io/v1alpha1
kind: Router
metadata:
  name: {{ include "whizard.router.crname" . }}
  namespace: {{ include "whizard.namespace" . }}
  labels:
    {{- if .Values.router.serviceReference }}
    "monitoring.whizard.io/service": "{{ .Values.router.serviceReference.namespace }}.{{ .Values.router.serviceReference.name }}"
    {{- else if .Values.service.enabled }}
    "monitoring.whizard.io/service": "{{ include "whizard.namespace" . }}.{{ include "whizard.service.crname" . }}"
    {{- end }}
    {{- include "whizard.labels" . | nindent 4 }}
spec:
  {{- if .Values.router.image }}
  image: "{{ .Values.router.image.repository }}:{{ .Values.router.image.tag }}"
  {{- else }}
  image: "{{ .Values.global.whizard.image.repository }}:{{ .Values.global.whizard.image.tag }}"
  {{- end }}
  replicas: {{ .Values.router.replicas }}

  {{- with .Values.router.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.router.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.router.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.router.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.router.securityContext }}
  securityContext:
    {{- toYaml . | nindent 4 }}
  {{- end }}  

  logLevel: {{ .Values.global.whizard.log.level }}
  logFormat: {{ .Values.global.whizard.log.format }}
  replicationFactor: {{ .Values.router.replicationFactor }}
  {{- with .Values.router.additionalFlags }}
  flags:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{ if .Values.router.genSignedCert }}
  httpServerTLSConfig:
    certSecret:
      name: {{ include "whizard.router.crname" . }}-router-tls-assets
      key: tls.crt
    keySecret:
      name: {{ include "whizard.router.crname" . }}-router-tls-assets
      key: tls.key
  {{- else }}
  {{- with .Values.router.httpServerTLSConfig }}
  httpServerTLSConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
