apiVersion: v1
kind: Service
metadata:
  name: devops-frontend
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: devops-apiserver
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    {{- include "apiserver.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    {{- include "apiserver.selectorLabels" . | nindent 4 }}