apiVersion: v1
appVersion: 0.1.0
description: WhizardTelemetryRuler is a tool for observability events alerting that can define alerting rules for K8s native events and K8s & KS auditing events, evaluate these rules on incoming events data, and send alerts to specified sinks like an HTTP endpoint.
name: whizard-telemetry-ruler
version: 0.1.0
