apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-pre-install"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install-job
        image: bitnami/kubectl
        command: 
          - /bin/sh
          - -c
          - |
            #!/bin/bash
            if kubectl get mutatingwebhookconfigurations istio-sidecar-injector-1-14-6 >/dev/null 2>&1; then
                kubectl delete mutatingwebhookconfigurations istio-sidecar-injector-1-14-6
            fi
            if kubectl get validatingwebhookconfigurations istio-validator-1-14-6-istio-system >/dev/null 2>&1; then
                kubectl delete validatingwebhookconfigurations istio-validator-1-14-6-istio-system
            fi
            if kubectl -n istio-system get deployment kiali-operator >/dev/null 2>&1; then
                kubectl -n istio-system delete deployment kiali-operator
            fi
            if kubectl -n istio-system get deployment jaeger-operator >/dev/null 2>&1; then
                kubectl -n istio-system delete deployment jaeger-operator
            fi
