apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-hooks
  namespace: {{ include "history.namespaceOverride" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-hooks
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
rules:
  - verbs:
      - 'create'
      - 'patch'
      - 'update'
      - 'get'
    apiGroups:
      - 'extensions.kubesphere.io'
      - 'kubesphere.io'
    resources:
      - '*'

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-hooks
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-hooks
    namespace: {{ include "history.namespaceOverride" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-hooks
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-hooks
  namespace: {{ include "history.namespaceOverride" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
spec:
  backoffLimit: 1
  template:
    metadata:
      name: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-hooks
      restartPolicy: Never
      containers:
        - name: annotate-job
          image: {{ .Values.hook.image.repo }}:{{ .Values.hook.image.tag }}
          command:
            - /bin/sh
            - -c
            - |
              {{ if eq .Values.enabled true }}
              kubectl annotate --overwrite extension whizard-notification logging.kubesphere.io/enable-notification-history=true
              {{ else }}
              kubectl annotate --overwrite extension whizard-notification logging.kubesphere.io/enable-notification-history=false
              {{ end }}