{{ if eq .Values.enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: vector-aggregator-notification-history
  namespace: {{ include "history.namespaceOverride" . }}
  labels:
    logging.whizard.io/vector-role: Aggregator
    logging.whizard.io/enable: "true"
stringData:
  notification-history.yaml: |
    transforms:
      notification_history_remapped:
        inputs:
        - http_dispatcher.notification_history
        source: |-
          . = parse_json!(.message)
          .timestamp = .notificationTime
        type: remap
{{- end}}