apiVersion: v1
kind: ConfigMap
metadata:
  {{- if .Values.configs.gpgKeysAnnotations }}
  annotations:
    {{- range $key, $value := .Values.configs.gpgKeysAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "name" "gpg-keys-cm") | nindent 4 }}
  name: argocd-gpg-keys-cm
  {{- if .Values.global.argocdNamespace }}
  namespace: {{ .Values.global.argocdNamespace }}
  {{- end }}
{{- with .Values.configs.gpgKeys }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
