# Default values for whizard-telemetry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Override the deployment name
##
nameOverride: ""

## Provide a name to substitute for the full names of resources
##
fullnameOverride: ""


global:
  rbac:
    create: true

## Enable Kubesphere extension registration
## 
kubeSphereExtensionEnabled: true

config:
  kubesphere:
    host: "http://ks-apiserver.kubesphere-system.svc:80"
    # username: "admin"
    # password: "P@88w0rd"
  monitoring:
    enabled: true
    endpoint: http://prometheus-k8s.kubesphere-monitoring-system.svc:9090
  observability:
    enabled: true 
    endpoint: "http://query-frontend-whizard-operated.kubesphere-monitoring-system.svc:10902"
  externalMonitoringTemplate: 
    enabled: false
    path: ""    # path and content are mutually exclusive. extraVolumeMounts and extraVolumes are configured, so you can load externalMonitoringTemplate through path.
    content: {}

apiserver:
  replicaCount: 1

  image:
    repository: kubesphere/whizard-telemetry-apiserver
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 9090

  resources: 
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 20m
      memory: 50Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  extraVolumeMounts: []
  ## Additional volumeMounts to the apiserver container.
  #  - name: example-config
  #   mountPath: /etc/kubesphere/example

  extraVolumes: []
  ## Additional volumes to the apiserver pod.
  #  - name: example-config
  #    emptyDir: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# For KubeSphere RBAC
ksRbac:
  create: true

ksServiceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""