apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}-controller-manager
  labels:
    app: gateway-controller-manager
    tier: controller
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiserver.service.type }}
  ports:
    - port: {{ .Values.apiserver.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: gateway-controller-manager
    tier: controller
    {{- include "gateway.selectorLabels" . | nindent 4 }}