apiVersion: iam.kubesphere.io/v1beta1
kind: RoleTemplate
metadata:
  annotations:
    iam.kubesphere.io/role-template-rules: '{"ks-project-gateway": "view"}'
  labels:
    iam.kubesphere.io/category: ks-gateway
    iam.kubesphere.io/scope: namespace
    kubesphere.io/managed: "true"
    iam.kubesphere.io/aggregate-to-viewer: ""
  name: ks-project-gateway-view
spec:
  description:
    en: 'View Project Gateway.'
    zh: '查看项目网关。'
  displayName:
    en: 'View Project Gateway.'
    zh: '查看项目网关。'
  rules:
  - apiGroups:
      - gateways.kubesphere.io
    resources:
      - '*'
    verbs:
      - get
      - list
  - apiGroups:
      - 'monitoring.kubesphere.io'
    resources:
      - ingresses
    verbs:
      - get
      - list

---
apiVersion: iam.kubesphere.io/v1beta1
kind: RoleTemplate
metadata:
  annotations:
    iam.kubesphere.io/role-template-rules: '{"ks-project-gateway": "manage"}'
    iam.kubesphere.io/dependencies: '["ks-project-gateway-view"]'
  labels:
    iam.kubesphere.io/category: ks-gateway
    iam.kubesphere.io/scope: namespace
    kubesphere.io/managed: "true"
    iam.kubesphere.io/aggregate-to-operator: ""
    iam.kubesphere.io/aggregate-to-admin: ""
  name: ks-project-gateway-manage
spec:
  description:
    en: 'Manage Project Gateway.'
    zh: '管理项目网关。'
  displayName:
    en: 'Manage Project Gateway.'
    zh: '管理项目网关。'
  rules:
  - apiGroups:
      - gateways.kubesphere.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - 'monitoring.kubesphere.io'
    resources:
      - ingresses
    verbs:
      - get
      - list

# workspace config
---
apiVersion: iam.kubesphere.io/v1beta1
kind: RoleTemplate
metadata:
  annotations:
    iam.kubesphere.io/role-template-rules: '{"ks-workspace-gateway": "view"}'
  labels:
    iam.kubesphere.io/category: ks-gateway
    iam.kubesphere.io/scope: workspace
    kubesphere.io/managed: "true"
    iam.kubesphere.io/aggregate-to-viewer: ""
  name: ks-workspace-gateway-view
spec:
  description:
    en: 'View Workspace Gateway.'
    zh: '查看企业空间网关。'
  displayName:
    en: 'View Project Gateway.'
    zh: '查看企业空间网关。'
  rules:
  - apiGroups:
      - gateways.kubesphere.io
    resources:
      - '*'
    verbs:
      - get
      - list
  - apiGroups:
      - 'monitoring.kubesphere.io'
    resources:
      - ingresses
    verbs:
      - get
      - list

---
apiVersion: iam.kubesphere.io/v1beta1
kind: RoleTemplate
metadata:
  annotations:
    iam.kubesphere.io/role-template-rules: '{"ks-workspace-gateway": "manage"}'
    iam.kubesphere.io/dependencies: '["ks-workspace-gateway-view"]'
  labels:
    iam.kubesphere.io/category: ks-gateway
    iam.kubesphere.io/scope: workspace
    kubesphere.io/managed: "true"
    iam.kubesphere.io/aggregate-to-operator: ""
    iam.kubesphere.io/aggregate-to-admin: ""
  name: ks-workspace-gateway-manage
spec:
  description:
    en: 'View Workspace Gateway.'
    zh: '管理企业空间网关。'
  displayName:
    en: 'View Workspace Gateway.'
    zh: '管理企业空间网关。'
  rules:
  - apiGroups:
      - gateways.kubesphere.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - 'monitoring.kubesphere.io'
    resources:
      - ingresses
    verbs:
      - get
      - list